baseURL: "https://www.bookproject.example/books/"
title: Book Publishing
paginate: 10
theme: papermod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
    disableXML: true
    minifyOutput: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Book Publishing"
    author: 
    # author: ["Me", "You"] # multiple authors
    hideSummary: true
    
    mainSections:
    - dracula
    - wuthering-heights
    
    featuredSections:
    - dracula 

    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowToc: false
    # comments: false
    # images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: Book Publishing
        # imageUrl: "#"
        # imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Book Publishing"
        Content: >
            This is a book project.


    socialIcons:
        # - name: twitter
          # url: "https://twitter.com/tarot_io/"
        # - name: email
          # url: "https://www.tarot.io/"
        #- name: RsS
        #  url: "index.xml"

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 100
    threshold: 0.1
    minMatchCharLength: 0
    keys:
      - title
      - permalink
      - summary
      - content   

taxonomies:
    category: categories
    tag: tags
    series: serieses

# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true

menu:
  main:
    - identifier: featured
      name: Featured
      url: /featured/
      weight: 10
    - identifier: list
      name: List
      url: /list/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 11
    - identifier: about
      name: About
      url: /about/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 15